server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: fashion-bestseller
  cloud:
    kubernetes:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
