server:
  port: 8083

management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: hot-deals
  cloud:
    kubernetes:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/