server:
  port: 8081


# Init Chaos Monkey for Spring Boot by profile
spring:
  application:
    name: toys-bestseller
  cloud:
    kubernetes:
      enabled: false


# Spring Boot Actuator Endpoint Chaos Monkey for Spring Boot
management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
